name: Build and Push Docker Image to Artifact Registry

on:
  workflow_run:
    workflows: ["Python CI"]
    types:
      - completed

jobs:
  build:
    # Conditionally run this job only on success of the Python CI workflow on the main branch
    if: github.ref == 'refs/heads/main' && github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Google Artifact Registry
      uses: docker/login-action@v1
      with:
        registry: europe-west1-docker.pkg.dev/mlops-389311/email-discriminator
        username: _json_key
        password: ${{ secrets.GCP_SA_KEY }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        platforms: linux/amd64
        tags: europe-west1-docker.pkg.dev/mlops-389311/email-discriminator/email-discriminator:1
